server:
  port: 8081
spring:
  application:
    name: user-service
eureka:
  instance:
    instance-id: user-8081-hystrix
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/
info:
  app.name: userService
  company: www.jleopard.org
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
